# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  dockerId: mattwatson1
  imageName: kongologym

steps:
- script: dotnet restore src/KongoloGym
  displayName: 'Restore dependencies'
- script: dotnet build --configuration $(buildConfiguration) src/KongoloGym
  displayName: '$(buildConfiguration) build'
- task: Docker@2
  inputs:
    containerRegistry: 'DockerHub ($(dockerId))'
    command: 'login'
- script: docker build -t $(dockerId)/$(imageName) .
  displayName: 'Docker Build'
- script: docker push $(dockerId)/$(imageName)
  displayName: 'Docker Push'