apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: kongologym
  name: kongologym
  selfLink: /api/v1/namespaces/default/services/kongologym
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    name: http
  - port: 443
    protocol: TCP
    targetPort: 443
    name: https
  selector:
    run: kongologym
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
